# -*- coding: utf-8 -*-
"""Indian Stock Market.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xs6nDbyiMq47-h0G9Gra276yMwjFAeMb

Importing Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt

"""Importing Dataset"""

tata_motors=pd.read_csv("TATAMOTORS.csv")
tata_steel=pd.read_csv("TATASTEEL.csv")
tcs=pd.read_csv("TCS.csv")

tata_motors.head()

tata_steel.head()













